name: Release Unsigned
on:
  workflow_dispatch:
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout builds
        uses: actions/checkout@main

      - name: Setup JDK 11
        uses: actions/setup-java@main
        with:
          java-version: 11
          distribution: adopt

      - name: Setup Android SDK
        uses: android-actions/setup-android@7c5672355aaa8fde5f97a91aa9a99616d1ace6bc # v2.0.10
      
      - name: Build Unsigned APK
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease
          
      - uses: actions/upload-artifact@main
        with:
          name: UnsignedAPK
          path: app/build/outputs/apk/release/app-release-unsigned.apk
