name: Release

on:
  # Trigger the workflow on pushes with a tag matching "v*"
  push:
    tags:
      - v*
  # Enable manual triggering of the workflow
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      
      - name: Setup credentials
        run: |
          base64 -d <<< "$KEYSTORE_BASE64" > $HOME/keystore.jks
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      
      - name: Get release tag
        id: release_values
        run: |
          echo "release_tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build Release APK
        run: |
          chmod +x ./gradlew
          ./gradlew app:assembleRelease \
            -Pandroid.injected.signing.store.file="$HOME/keystore.jks" \
            -Pandroid.injected.signing.store.password="$KEYSTORE_PASSWORD" \
            -Pandroid.injected.signing.key.alias="$KEY_ALIAS" \
            -Pandroid.injected.signing.key.password="$KEY_PASSWORD"

          mv app/build/outputs/apk/release/app-release.apk Vencord-$TAG.apk
        env:
          TAG: ${{ env.release_tag }}
          KEY_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Upload APK to GitHub Release
        run: |
          gh release create $TAG Equicord-$TAG.apk --title "Equicord $TAG" --notes "Release of Equicord $TAG"
        env:
          TAG: ${{ env.release_tag }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
