name: Release Full

on:
  workflow_dispatch:   # Allows manual triggering
  push:
    branches:
      - main           # Triggered on push to main branch (e.g., after a merge)

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2.0.10

      - name: Setup credentials
        run: |
          echo "Decoding and setting up Keystore..."
          base64 -d <<< "$KEYSTORE_BASE64" > $HOME/keystore.jks
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      - name: Build APK
        run: |
          chmod +x ./gradlew
          ./gradlew app:assembleRelease \
            -Pandroid.injected.signing.store.file="$HOME/keystore.jks" \
            -Pandroid.injected.signing.store.password="$KEYSTORE_PASSWORD" \
            -Pandroid.injected.signing.key.alias="$KEY_ALIAS" \
            -Pandroid.injected.signing.key.password="$KEY_PASSWORD"
        env:
          KEY_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: VencordDev
          path: app/build/outputs/apk/release/app-release.apk

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.sha }}
          release_name: "Release for Commit ${{ github.sha }}"
          body: "Release for commit ${{ github.sha }} pushed to main"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/release/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive
